apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  replicas: 3 # El número de réplicas que deseas ejecutar
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: mi-aplicacion
        image: NOMBRE_DE_TU_IMAGEN_DOCKER:TAG
        ports:
        - containerPort: 5000 # El puerto en el que se ejecuta tu aplicación
